services:
  frontend:
    restart: always
    env_file:
      - ../frontend/.env
    environment:
      - TZ=UTC
    build:
      context: ../frontend
      target: dev
    volumes:
      - ../frontend/assets:/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    networks:
      - clipfinity

  backend:
    restart: always
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ../backend/.env
    environment:
      - TZ=UTC
    build:
      context: ../backend
      target: dev
    volumes:
      - ../backend/assets:/assets
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/backend`)"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/backend"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
    networks:
      - clipfinity

  minio:
    restart: always
    volumes:
      - minio_data:/data
    env_file:
      - ../minio/.env
    environment:
      - TZ=UTC
    build:
      context: ../minio
      target: dev
    ports:
      - "8002:9001"   # Console UI
    networks:
      - clipfinity

  database:
    restart: always
    volumes:
      - database_pgdata:/var/lib/postgresql/data
    env_file:
      - ../database/.env
    environment:
      - TZ=UTC
    build:
      context: ../database
      target: dev
    networks:
      - clipfinity

  pgadmin:
    restart: always
    volumes:
      - ../pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "8001:80"
    env_file:
      - ../pgadmin/.env
    environment:
      - TZ=UTC
    build:
      context: ../pgadmin
      target: dev
    depends_on:
      database:
        condition: service_healthy
    networks:
      - clipfinity

  gateway:
    restart: always
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker=true --providers.docker.exposedbydefault=true --ping=true --log=true --log.level="TRACE" --accesslog=true --tracing=true
    ports:
      # The HTTP (AND S) port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
    build:
      context: ../gateway
      target: dev
    networks:
      - clipfinity

networks:
  clipfinity:
    driver: bridge

volumes:
  database_pgdata:
  minio_data:
